[package]
name = "test262-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
crustyjs-core = { path = "../core", package = "core" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2"
colored = "2"
rayon = "1"
clap = { version = "4", features = ["derive"] }
